name: Bug Report
description: File a bug report to help us improve
title: '[Bug]: '
labels: ['bug', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Install the package with `npm install @beat-parser/core`
        2. Import the library `import { BeatParser } from '@beat-parser/core'`
        3. Create an instance...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { BeatParser } from '@beat-parser/core';
        
        const parser = new BeatParser();
        // ... your code here
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: Please include any error messages or relevant log output
      render: text
      placeholder: Paste error messages or logs here...
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Package Version
      description: What version of @beat-parser/core are you using?
      options:
        - 1.0.0
        - Other (please specify in additional info)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 13.5, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Add any other context about the problem here...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true